service:
  env: development
  secret: $UPTRACE_SECRET

site:
  url: http://localhost:14318
  ingest_url: http://localhost:14318?grpc=4317

listen:
  http:
    addr: :80
  grpc:
    addr: :4317

auth:

seed_data:
  update: true
  delete: false
  users:
    - key: admin
      name: BookFlow Admin
      email: $UPTRACE_ADMIN_EMAIL
      password: $UPTRACE_ADMIN_PASSWORD
      email_confirmed: true
  user_tokens:
    - key: admin-token
      user_key: admin
      token: $UPTRACE_USER_TOKEN
  orgs:
    - key: bookflow
      name: BookFlow
  org_users:
    - key: bookflow-admin
      org_key: bookflow
      user_key: admin
      role: owner
  projects:
    - key: bookflow-local
      name: BookFlow local
      org_key: bookflow
  project_tokens:
    - key: bookflow-local-token
      project_key: bookflow-local
      token: $UPTRACE_PROJECT_TOKEN
  project_users:
    - key: bookflow-local-admin
      project_key: bookflow-local
      org_user_key: bookflow-admin
      perm_level: admin

ch_cluster:
  cluster: uptrace1
  replicated: false
  distributed: false
  shards:
    - replicas:
        - addr: uptrace-clickhouse:9000
          database: uptrace
          user: uptrace
          password: $UPTRACE_CLICKHOUSE_PASSWORD
  dial_timeout: 3s
  write_timeout: 5s
  max_retries: 3
  max_execution_time: 15s

pg:
  addr: uptrace-postgres:5432
  user: uptrace
  password: $UPTRACE_POSTGRES_PASSWORD
  database: uptrace

ch_schema:
  compression: ZSTD(1)
  spans_index: { storage_policy: default }
  spans_data: { storage_policy: default }
  span_links: { storage_policy: default }
  logs_index: { storage_policy: default }
  logs_data: { storage_policy: default }
  events_index: { storage_policy: default }
  events_data: { storage_policy: default }
  metrics: { storage_policy: default }

redis_cache:
  addrs:
    1: uptrace-redis:6379
  username: ""
  password: $UPTRACE_REDIS_PASSWORD
  db: 0

certmagic:
  enabled: false

mailer:
  smtp:
    enabled: false

self_monitoring:
  dsn: http://$UPTRACE_PROJECT_TOKEN@uptrace:80?grpc=4317

logging:
  level: INFO
